### ISSUE TITLE
`pt` is accepted but `pT` is not

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/vector#121]
For example:

```python
>>> import vector
>>> vector.obj(pt=0, eta=0, phi=0, E=0)
vector.obj(pt=0, phi=0, eta=0, E=0)
>>> vector.obj(pT=0, eta=0, phi=0, E=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/vector/_backends/object_.py", line 2775, in obj
    return _gather_coordinates(
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/vector/_backends/object_.py", line 1524, in _gather_coordinates
    raise TypeError(
TypeError: unrecognized combination of coordinates, allowed combinations are:

    (2D) x= y=
    (2D) rho= phi=
    (3D) x= y= z=
    (3D) x= y= theta=
    (3D) x= y= eta=
    (3D) rho= phi= z=
    (3D) rho= phi= theta=
    (3D) rho= phi= eta=
    (4D) x= y= z= t=
    (4D) x= y= z= tau=
    (4D) x= y= theta= t=
    (4D) x= y= theta= tau=
    (4D) x= y= eta= t=
    (4D) x= y= eta= tau=
    (4D) rho= phi= z= t=
    (4D) rho= phi= z= tau=
    (4D) rho= phi= theta= t=
    (4D) rho= phi= theta= tau=
    (4D) rho= phi= eta= t=
    (4D) rho= phi= eta= tau=
```

I know from https://github.com/scikit-hep/vector/issues/78 that combinatorics are intended to be kept low, but it seems like `pT` should work if things like `E`/`e` and `M`/`m` are accepted,

**Comment by jpivarski** [comment]
Adding methods/properties (what you get _out_ of a vector/array of vectors) is easy; it happens in a centralized place.

Adding arguments to constructors (what you put _in_ to make one) is hard; it necessarily happens in many different places, and we have to work hard to make sure they're all consistent. For that reason, I wanted to keep that list small and only begrudgingly took the lowercase/capitalized versions of `e`, `E`, `m`, and `M`. The reason for having both of these is that there are arguments for why they _must_ be lowercase and arguments for why they _must_ be capitalized.

   * They must be lowercase because it's a Python convention that arguments of a function (including constructors) are lowercase.
   * They must be capital because `e` doesn't look like "energy". It makes a physicist think of exponentiation. The convention of using a capital `E` is very deeply set in previous Lorentz vector libraries. The argument for `M` isn't quite as strong (though there are previous libraries that use `M` in addition to `m`) and that's why it wasn't added at first; it was added later for consistency because consistency makes an interface "guessable," usable without having to refer to the documentation all the time.

An argument similar to the second bullet point could apply to `pT`, capitalizing the second character. But (1) the methods/properties also don't support `pT` and nobody's complained about that (maybe because tab-completion answers the question?), and (2) I don't think there's a tradition of previous Lorentz libraries spelling it with a capitalized second character. Am I wrong? If there is a library that has spelled it this way, is it a library that has every spelling under the sun (e.g. _also_ `PT` and maybe even `Pt`) and do we have any way of knowing that this spelling is widely used?

If need be, we can add a new constructor argument and make it consistent across the codebase, but we have to ask these questions first because we should have some resistance/push-back to see if it's really something we want to support forever.

**Comment by eduardo-rodrigues** [comment]
Agree. I would not open the pandora box here. And in fact `pt` has been used in may older versions for vectors and alike - Henry's module, what got into `scikit-hep` early on, etc.

**Comment by masonproffitt** [comment]
I think Pythia is probably the highest profile example of a library using only `pT` (<https://pythia.org/manuals/pythia8306/FourVectors.html#anchor19>). [pyjet](https://github.com/scikit-hep/pyjet) seems to be a bit inconsistent (I'm seeing both `pT` and `pt`). [ROOT](https://root.cern.ch/doc/master/classTLorentzVector.html#a5fc848d55ec9f94ec554bc183d4f78ac) is historically based on `Pt`, but that's of course driven by the capitalization conventions of class methods.

I guess mainly I don't see an argument against `pT` that wouldn't also apply to `M`, for example.

**Comment by eduardo-rodrigues** [comment]
Most probably. But one should not be devising Pythonic conventions for a Python library taking as examples C++ libraries that many agree do not have very common conventions in the first place. Agreed that there are some inconsistencies out there also in Python libraries. Personally I would not mind lowercase `e` and `m` and would not be confused - anyway seriously using the library will look at the convention to create/annotate a Lorentz vector after all.

**Comment by jpivarski** [comment]
The question we should be asking is: how likely is it that someone's going to type "pT", it doesn't work, and they get frustrated wondering why it doesn't work?

The argument for "M" is because someone might be switching a vector from energy to mass or using both in the same analysis, and the fact that "E" is capitalized might make them guess "M", so that's why I conceded on that one.

For someone to guess "pT", it's not likely that they'd be led astray by the capitalization of "E" or "M" because it's in a different slot, and familiarity with other libraries isn't going to push them that way unless Pythia is the main one that they know.

If they first try "pT" and get the above error message, would that likely be enough to make them say, "Oh! Of course..." and change their code? (Maybe such an argument would have worked with "M" as well, but I think the push for "M" was higher for other reasons.)

**Comment by masonproffitt** [comment]
At least for me, seeing any capitalization at all (`M` and especially `E`) makes me think that anything that is normally capitalized in non-code text should be capitalized here, hence `pT`. Conversely, `pt` makes me expect `e` and `m` or `mass`.

Maybe the more important thing to do is improving the error message. There's no mention of any version of `pT` or `E` or `mass` in the error, so I could easily see somebody indeed getting frustrated and wondering why it's not working. These are in the documentation but not the error text. If the capitalization conventions were right there in the error, then I really don't think anybody could get too frustrated or confused.

**Comment by jpivarski** [comment]
I think I'm going to make this `wontfix` because there will always be a tension between wanting additional spellings and wanting to keep the set of spellings at a minimum. At the moment, the spelling of input argument names is a consistent subset of the output properties—it's not like we can take `pT` as an input argument but only `pt` as an output property, or vice-versa, or some other combination. `E` and `M` have both lower-case and capitalizations, but `pt` and others do not. You might have to lean on tab-completion or have a cheat-sheet, but it's not _wrong_.
