### ISSUE TITLE
Possible exporting of generically useful methods from `vector` without construction of a `vector.obj`

### ISSUE THREAD

**Issue by phinate** [scikit-hep/vector#146]
I've seen it a couple times now where in some non-ROOT code, things like deltaR, bounding phi etc. are reimplemented in pure python because there isn't a standardised lib for these generically useful ops.

Would it be within (or possibly an expansion of) the scope of the `vector` package to be able to export some of the generically useful functions that don't require vectors themselves? For example, there's no need for me to construct a whole  separate object if I have two columns of phi in an `ak.Array` from two jets that I want to handle, but it would be really nice if there was a standardized set of methods I could grab from a reliable package to ensure no duplicity, and probability for human error, such as making sure I remember to map the delta phi to [-pi, pi].

This could potentially be it's own package, but given that `vector` is already somewhat awkward/numpy aware, it doesn't seem too out of the ordinary to have some stand-alone utility methods that work on those objects as well.

Just wanted to throw this out there -- and thanks for the work on the package itself!

**Comment by jpivarski** [comment]
Well, we could expose those compute functions as a public API. They require no more information than necessary to compute the function (i.e. 2D functions only need azimuthal coordinates, 3D functions don't need a time component), and they don't need (or want) any objects or multicomponent arrays. (Anything that duck-types with math operators and functions in the `lib` first argument, which can be equal to `numpy`, will pass through these functions, returning a tuple if the result is not a scalar. These functions also have zero `if` statements or loops.)

We'd have to somehow deal with the fact that there are so many coordinate systems—that's why `deltaR2` has so many implementations: there are 2 x 2 x 3 = 12 combinations of left and right vector coordinates. The functions themselves are organized by a naming convention, and the dict in the module looks then up by coordinate system combination and specifies how to interpret the output tuple (what coordinate system, if any; `deltaR2` returns a scalar, so it's not relevant in this case). That could all be simplified, at a cost, by only exposing the Cartesian cases.

On the other hand, about not having to pull in extraneous information, you know that if you want to compute a spatial function like `deltaR`, you don't need to make a 4D vector (or array of vectors). You can make a 3D vector (or array of vectors) and not have to invent a time coordinate. If you want to compute a quantity like `deltaphi`, you only need to make 2D vectors. What the explicit object or array is doing for you is keeping track of the coordinate systems of the inputs and (possibly) outputs of the function. Like the functions, they don't require any more components than are needed to compute the function.

So the objects/arrays purchase a bookkeeping benefit, and I don't know what mental cost they impose. I'm all for making things simpler when the mental cost/benefit is favorable, I just don't see how that's the case here.
