### ISSUE TITLE
Boosting (might) remove the Momentum nature of a 4D Vector

### ISSUE THREAD

**Issue by aphecetche** [scikit-hep/vector#160]
I'm a bit confused as to why `boost` is "removing" the momentum nature of a 4D vector (which precludes the usage of `mass` on the boosted vector for instance) :  

```python
import vector 
print(vector.__version__)
v=vector.obj(px=1,py=1,pz=1,e=3)
print(v,type(v))
boosted = v.boost(vector.obj(x=0.1,y=0.1,z=0.9))
print(boosted,type(boosted))
```

```shell
0.8.4
vector.obj(px=1, py=1, pz=1, E=3) <class 'vector._backends.object_.MomentumObject4D'>
vector.obj(x=1.9165095106993202, y=1.9165095106993202, z=9.24858559629388, t=9.943960626489654) <class 'vector._backends.object_.VectorObject4D'>
```

Note that the expected (at least to me :wink: ) behaviour is achieved if I define the velocity vector using `px,py,pz` (instead of `x,y,z` as above) : 

```python
v=vector.obj(px=1,py=1,pz=1,e=3)
print(v,type(v))
boosted = v.boost(vector.obj(px=0.1,py=0.1,pz=0.9))
print(boosted,type(boosted))
```

```shell
vector.obj(px=1, py=1, pz=1, E=3) <class 'vector._backends.object_.MomentumObject4D'>
vector.obj(px=1.9165095106993202, py=1.9165095106993202, pz=9.24858559629388, E=9.943960626489654) <class 'vector._backends.object_.MomentumObject4D'>
```

is that expected ? 

Thanks (and Happy New Year, btw)

**Comment by jpivarski** [comment]
"Momentumness" is currently passed on through the following rule: if all input arguments of a function (including `self`) are momentum-like, then the output will be momentum-like. If any is not, the output is not. Both of the examples you're showing above are following that rule.

A secondary question is whether that's the _right_ rule to follow. Having too many exceptions would make it hard to predict what's going to happen, but if a particular combination just doesn't make sense, then perhaps it should be handled specially. In this case, `self` is a momentum and the boosting vector might be purely geometric, not a momentum. At the moment, I can only think of one kind of vector that is not momentum—a position vector—and it wouldn't even make sense to talk about boosting that. If we wanted to get restrictive, maybe we should say that the non-`self` argument of `boost` should _only_ be a momentum vector?

As for the distinction between momentum and non-momentum vectors, it's usually not going to prevent you from calculating something. I think all of the momentum-specific properties and methods are just synonyms of properties and methods with different names. For instance, `mass` is the same thing as `tau`, the proper time component of a purely geometric vector. The only reason this distinction between momentum-like and non-momentum-like vectors exists is so that we don't get into a situation where we'd be calculating the proper time between two space-time events with a word like "mass," which would be semantic nonsense.

**Comment by jpivarski** [comment]
I think this answers the question and I'm cleaning up issues so that I have a better sense of what work needs to be done. If you have further comments, I'll see them and respond!
