### ISSUE TITLE
Numba: 'IndexedArrayType' object has no attribute 'arraytype'

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/vector#161]
### Version of Awkward Array

1.5.1

### Description and code to reproduce

I'm trying to iterate over a record in numba with awkward + vector using the simplified function below (reproducer is below). However, the numba compilation fails with:

```
Traceback (most recent call last):
  File "/software/rehlers/dev/mammoth/projects/exploration/repro_numba.py", line 28, in <module>
    reproducer()
  File "/software/rehlers/dev/mammoth/projects/exploration/repro_numba.py", line 25, in reproducer
    repro(generator_like_jet_constituents=a.constituents)
  File "/software/rehlers/dev/mammoth/.venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/software/rehlers/dev/mammoth/.venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.IntrinsicCallConstraint object at 0x7fd2e2a61ee0>.
'IndexedArrayType' object has no attribute 'arraytype'
During: typing of intrinsic-call at /software/rehlers/dev/mammoth/projects/exploration/repro_numba.py (19)
Enable logging at debug level for details.

File "repro_numba.py", line 19:
def repro(
    <source elided>
        s = 0
        for generator_like_constituent in generator_like_constituents:
        ^
```

(first reported on gitter because I was having some trouble pickling up the array. Jim clarified that I needed to use to_buffers/from_buffers to keep the exact layout intact)

It can reproduced with the [this pkl](https://cernbox.cern.ch/index.php/s/rZsnLtwtWoFPniA) and using the code below:

```python
import pickle

import awkward as ak
import numba as nb


@nb.njit  # type: ignore
def repro(
    generator_like_jet_constituents: ak.Array,
) -> None:
    for i, generator_like_constituents in enumerate(generator_like_jet_constituents):
        s = 0
        for generator_like_constituent in generator_like_constituents:
            s += generator_like_constituent.pt

def reproducer() -> None:
    with open("repro.pkl", "rb") as f:
        a = ak.from_buffers(*pickle.load(f))
    repro(generator_like_jet_constituents=a.constituents)

if __name__ == "__main__":
    reproducer()
```

Note that the pickle contains some Momentum4D vectors. I'm not yet sure if I've found a bug or am overlooking something, but I suspect it has something to do with the layout. Thanks!

**Comment by jpivarski** [comment]
@raymondEhlers Your reproducer also needed

```python
vector.register_awkward()
```

but since you were talking about the "no attribute 'arraytype'" error, rather than a "no `pt` component" error, you must have had that in your example. (Or if not globally set, at least it was a behavior passed through the object, as fastjet does.)

Anyway, what went wrong here is that vector components, like `rho` (i.e. `pt`), might be NumpyArrays in the Awkward Array or they might be IndexedArrays of NumpyArrays (or IndexedArrays of IndexedArrays of NumpyArrays, etc). No other Awkward layout types would be possible, except maybe EmptyArrays, but then I don't know what dtype it should report (float64 always?). The IndexedArray case was overlooked.

With this fix, you'd be able to run your code without packing the array first, which just means that the indirection will be handled at runtime, rather than making a leaner array up-front. Whether that's faster or slower depends on the size of the array and the amount of indirection. I can't say that this will help the performance of your case, but it's more correct and the error message should be gone.

**Comment by jpivarski** [comment]
I just checked and there are no _Numba_ types associated with EmptyArrays (i.e. no "`EmptyArrayType`" like "`NumpyArrayType`" or "`IndexedArrayType`"). EmptyArrays are either replaced with NumpyArrays upon entering a JIT-compiled function or there's an error message further upstream. (I didn't test it.) Since EmptyArrays have unknown type, in principle it should fail to compile.

That's not your case, I'm just thinking about possible future errors, similar to this one. `NumpyArrayType` and `IndexedArrayType` is the complete set of types that components can be allowed to have. (I'm not thinking deeply about `VirtualArrayType` because it will be removed in v2, anyway.)

**Comment by raymondEhlers** [comment]
Thanks for the fix! You're right that the vector behavior was passed through the pickled object. I overlooked the importance of that in the reproducer - my apologies (I think I played with it at the time in the reproducer, but I don't recall it making a difference, so I left it out then. But your description for why it matters makes sense). When there's a new release, I'll remove the `ak.packed` call and report back here if there are any issues. (I didn't profile it, but didn't notice any difference in runtime, so I think the performance is fine with or without packed). Thanks again!
