### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/vector#17]
Hi, not sure where to put this but I wanted to check that the work I did for coffea vectors will transfer seamlessly to this when it is ready. I have the following [classes](https://coffeateam.github.io/coffea/modules/coffea.nanoevents.methods.vector.html) (implementation [here](https://github.com/CoffeaTeam/coffea/blob/master/coffea/nanoevents/methods/vector.py)) and was wondering if you could review the naming convention and see if it matches the plans for this library, at least for the member attributes. I see that the ROOT TVectors prefer to avoid using `r` and `rho` for ambiguity's sake since depending where you look you find `r` for the 2D polar radius and `rho` for the 3D distance and vice-versa (e.g. [TVector](https://root.cern.ch/doc/master/classTVector3.html) vs. https://en.wikipedia.org/wiki/Spherical_coordinate_system)
In addition, I wonder if the inheritance approach will be taken for this library or not (I'm not sure myself if it makes sense) and if there are also plans for Point and "Point with origin" classes?

**Comment by nsmith-** [comment]
P.S. I just pushed a much more thoroughly documented module to help with this.

P. P. S. I would happily make a PR with the contents of that module so non-coffea users can have something to get started with on awkward1. I feel like awkward without vector mixins is like cake without ice cream

**Comment by donalrinho** [comment]
Hi all - I just wanted to chip in here to say that some FCC studies that I'm starting [here](https://github.com/donalrinho/fcc_python_tools) with uproot and awkward will benefit a lot from vector. I anticipate a good amount of uptake from people just starting FCC studies, so it will be great to have vector as part of the setup. 

On this note - it may be that Coffea can help us too, rather than me reinventing the wheel! I'm coming to this work from a flavour physics perspective, so building lots of exclusive decay modes and studying the momentum, impact parameter, lifetime resolutions e.t.c.

**Comment by henryiii** [comment]
I finally released Hist 2.0, so this will be my next (large) priority. I have a talk to write for Wednesday, so likely after that? Help and example appreciated!

**Comment by eduardo-rodrigues** [comment]
For reference - when discussing naming conventions, hence the API, we should not forget all that we're done in the past and is still available in the `scikit-hep` metapackage, see `https://github.com/scikit-hep/scikit-hep/tree/master/skhep/math` . I will be involved in the discussions for sure :-).
