### ISSUE TITLE
feat: add rapidity option for deltaR

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/vector#174]
Solely as a convenience, it would be helpful if an option to use rapidity could be added to `deltaR` (to be totally explicit, sqrt(dy ** 2 + dPhi ** 2) in addition to the current sqrt(deta ** 2 + dphi ** 2))

- fastjet uses [rapidity by default](http://fastjet.fr/repo/doxygen-3.4.0/classfastjet_1_1PseudoJet.html#a48e5e691362058354f940ecf748b3d07)
- `TLorentzVector` has as an [option to use rapidity](https://root.cern.ch/doc/master/classTLorentzVector.html#af2d46bf60f59486931ae153f5be01fa5) (it use eta by default)
- `ROOT::Math` puts it under a separate function [deltaRapidityPhi(...)](https://root.cern.ch/doc/master/namespaceROOT_1_1Math_1_1VectorUtil.html#a297df1d6e6d150508e8d3c1e492bbc61)

I'm not familiar enough with the design of `vector` to suggest which is the best way to add it in. I also know that it's quite trivial to implement by hand, so it's not a huge priority. But I think it would be a nice addition.

Thanks for consideration!

**Comment by jpivarski** [comment]
This is a reasonable request. Since Vector already has a "rapidity" function and this new function (I prefer `ROOT::Math`'s approach here) would be very much like `deltaR`, I'll talk through my process for adding it.

First off, I looked for all of the files that mention "`deltaR`".

```bash
$ fgrep -rl deltaR src/vector | fgrep -v '.pyc'
src/vector/_methods.py
src/vector/_compute/spatial/__init__.py
src/vector/_compute/spatial/deltaR2.py
src/vector/_compute/spatial/deltaR.py
src/vector/_backends/numba_object.py
```

I was about to say, "now we do the same thing, but with "`deltaRapidityPhi`". But as it turns out, I _do_ need to use special knowledge as an author: "`deltaRapidityPhi`" is going to be a Lorentz function (4D), whereas "`deltaR`" is just a Spatial function (3D), because rapidity needs to know about the particle mass. So this isn't going to be just naively adding a new function alongside the old one—it's going to be a little more involved.

In these five search hits, `src/vector/_methods.py` is what defines the user-level interface to the methods (independent of how they're calculated and what backend they're on), `src/vector/_compute/spatial/deltaR.py` calculates it in a duck-typed way, and we also have `src/vector/_compute/spatial/deltaR2.py` because any square root function also has a version of the function without the square root. In case you're planning on squaring it right away, you can save some computation. In principle, the backends should not need specialized code, but Numba does (a little bit, in a generalized way).

Let's start by writing the new "`deltaRapidityPhi2`" function. It goes in a different subdirectory of `compute`: `compute/lorentz`.

In `src/vector/_compute/spatial/deltaR2.py`, we see a lot of functions. They all return ΔR of two vectors, given as components, along with `lib`, which is usually the `numpy` module. There are strong constraints on these functions, such as a lack of any branching (`if`) or looping (`for`), because they have to duck-type into all the backends, and we want to keep our options open for future backends (e.g. SymPy). These functions are collected into a `dispatch_map` (a dict of coordinate combinations, function objects, and signatures), and all control flow comes in through the `dispatch` function.

The Planar functions have 3 coordinate systems, Spatial functions have 6 coordinate systems, and Lorentz functions have 12 coordinate systems. In `src/vector/_compute/spatial/deltaR2.py`, there are 36 functions because of the 6×6 possible coordinate systems of two Spatial vectors. In the Lorentz functions, we never write out 12×12 = 144 functions longhand, so let's get an example to copy. It needs to be some other Lorentz function of two vectors (not a vector and a scalar, or only one vector, etc.). `src/vector/_compute/lorentz/isclose.py` is a good model because it takes two vectors sa input and mostly defers to other functions, as we'll be deferring to `rapidity` and `deltaphi2`.

Following `isclose`, the 144 functions are generated by a `make_conversion` function, which runs at startup, filling the `dispatch_map`. Our new function will be calling `rapidity` (a Lorentz function, using all three types of coordinates: azimuthal, longitudinal, and temporal) and `deltaphi` (a Planar function, which only uses azimuthal coordinates). Since we'll just be _calling_ `rapidity` with its arguments, we won't need to do nearly as much `if azimuthal1 is AzimuthalXY`, etc., because we'll just be pulling the appropriate `rapidity` function out of its `dispatch_map`.

This ought to do it:

```python
def make_conversion(
    azimuthal1, longitudinal1, temporal1, azimuthal2, longitudinal2, temporal2
):
    planar_deltaphi, _ = deltaphi.dispatch_map[azimuthal1, azimuthal2]
    lorentz_rapidity1, _ = rapidity.dispatch_map[azimuthal1, longitudinal1, temporal1]
    lorentz_rapidity2, _ = rapidity.dispatch_map[azimuthal2, longitudinal2, temporal2]

    def f(
        lib,
        coord11,
        coord12,
        coord13,
        coord14,
        coord21,
        coord22,
        coord23,
        coord24,
    ):
        return (
            planar_deltaphi(lib, coord11, coord12, coord21, coord22)**2
            + (
                lorentz_rapidity1(lib, coord11, coord12, coord13, coord14)
                - lorentz_rapidity2(lib, coord21, coord22, coord23, coord24)
            )**2
        )

    dispatch_map[
        azimuthal1, longitudinal1, temporal1, azimuthal2, longitudinal2, temporal2
    ] = (f, float)
```

This function gets called the same way as in `isclose`, so I'll just copy that part. Also, the `dispatch` function is just like `isclose`, except that `deltaRapidityPhi2` has no non-vector arguments (`rtol`, `atol`, `equal_nan`), so I just remove those.

That's just the function for computing `deltaRapidityPhi2`. We'll also need to add it as a method to all vectors, so that it can be invoked. That's in `src/vector/_methods.py`: we can see `deltaR` as a method of `VectorProtocolSpatial`, which defines a protocol for typing but does not implement it, and as a method of `Spatial`, which actually implements it. Our new method belongs in `VectorProtocolLorentz` and `Lorentz`, however. I'll put it under `rapidity` (maintaining order is important).

```python
    def deltaRapidityPhi2(self, other: "VectorProtocol") -> ScalarCollection:
        r"""
        Square of the sum in quadrature of
        :doc:`vector._methods.VectorProtocolPlanar.deltaphi` and the difference in
        :doc:`vector._methods.VectorProtocolLorentz.rapidity` of the two vectors:

        $$\Delta R_{\mbox{rapidity}} = \Delta\phi^2 + \Delta \mbox{rapidity}^2$$
        """
        raise AssertionError
```

and

```python
    def deltaRapidityPhi2(self, other: VectorProtocol) -> ScalarCollection:
        from vector._compute.lorentz import deltaRapidityPhi2

        return deltaRapidityPhi2.dispatch(self, other)
```

Now I should be able to test it.

```python
>>> import vector
>>> one = vector.obj(x=1.1, y=2.2, z=3.3, t=4.4)
>>> two = vector.obj(x=1.0, y=2.0, z=-3.0, t=4.0)

>>> one.deltaRapidityPhi2(two)
3.7865663081964707

>>> one.deltaphi(two)**2 + (one.rapidity - two.rapidity)**2
3.7865663081964707
```

Looks good to me. Now I'll just finish off by also doing `deltaRapidityPhi`, which I define in terms of `deltaRapidityPhi2`, not just by copying it and wrapping the result in `lib.sqrt`. (We want any bug-fixes in `deltaRapidityPhi2` to propagate to `deltaRapidityPhi`.)

Now the other files that matched `deltaR`: `src/vector/_compute/spatial/__init__.py` loads all of the functions on startup, which I guess isn't necessary (because my test worked without me adding `deltaRapidityPhi2` to `src/vector/_compute/lorentz/__init__.py`). It might be a future optimization to remove that. But for now, I'm sticking with the pattern.

The last file that has to be touched is `src/vector/_backends/numba_object.py`. There, `"deltaR"` and `"deltaR2"` are strings in a list called `spatial_binary_methods`. Everything in that list is defined as a [Numba extension](https://numba.pydata.org/numba-doc/latest/extending/index.html) in bulk because they all have the same signatures. Our new functions are unlike any that exist so far, since they're Lorentz, not Planar or Spatial, and they're binary methods. There's already a bulk-handling of `general_binary_methods`, but these are functions that apply to all Planar, Spatial, and Lorentz: we want just the latter. I'll just have to add a new handler for `lorentz_binary_methods`, and then we'll have it forever.

Fortunately, the future existence of `lorentz_binary_methods` was already anticipated. The code was there in the function that makes Numba extensions; there just hasn't been a need to call it, yet. It worked right away.

```python
>>> import vector
>>> import numba as nb
>>> one = vector.obj(x=1.1, y=2.2, z=3.3, t=4.4)
>>> two = vector.obj(x=1.0, y=2.0, z=-3.0, t=4.0)

>>> @nb.njit
... def f(one, two):
...     return one.deltaRapidityPhi(two)
... 
>>> f(one, two)
1.945910149055313

>>> @nb.njit
... def f(one, two):
...     return one.deltaRapidityPhi2(two)
... 
>>> f(one, two)
3.7865663081964707
```

PR #175 checks in all the changes I talked about above. Could you please add some tests? (The `tests` directory is well organized, with lots of examples.) If you can do that, I'll merge it and release a version. Thanks!

**Comment by raymondEhlers** [comment]
Hi Jim, thanks so much! I very appreciate both you detailing your thought process, as well as implemented the improvement itself. I apologize that I haven't found the time to add the simple tests - I know it's not very much work, especially compared to the implementation, but we're very deep in a conference rush, and I just haven't found the time. The conference is in early April, so I'll come back to this again then. Thanks again!
