### ISSUE TITLE
`q**2` is always positive for vector.MomentumObject4D

### ISSUE THREAD

**Issue by simonthor** [scikit-hep/vector#443]
### Vector Version

1.3.1

### Python Version

3.11.4

### OS / Environment

Kubuntu 22.04
vector is installed via pip inside a conda environment

### Describe the bug

When calculating `q**2` of a 4-vector that is created from `vector.obj`, the value is always positive, even when it should not be:
```python
>>> vector.obj(E=1, px=1, py=1, pz=1)**2
2.0000000000000004
```
For numpy vector arrays, the behavior is correct and as expected:
```python
>>> vector.array({"E": [1], "px": [1], "py": [1], "pz": [1]})**2
array([-2.])
```
I have not tested other backends (e.g. awkward).

**Comment by jpivarski** [comment]
If the backends differ, that's definitely a bug (and hard to see how it happened, since the backends use the same compute functions).

The rules for dealing with spacelike and negative-timelike 4-vectors were taken from ROOT: they're supposed to do the same thing as `TLorentzVector` and `Math::LorentzVector`. Checking this example with ROOT:

```c++
root [0] TLorentzVector v(1, 1, 1, 1);
root [1] v*v
(double) -2.0000000
```

Yes, it should be `-2`. The NumPy and Awkward backends get it right, but the object backend (oddly!) gets it wrong:

```python
>>> vector.array({"E": [1], "px": [1], "py": [1], "pz": [1]})**2
array([-2.])

>>> ak.zip({"E": [1], "px": [1], "py": [1], "pz": [1]}, with_name="Momentum4D")**2
<Array [-2] type='1 * int64'>

>>> vector.obj(E=1, px=1, py=1, pz=1)**2
2.0000000000000004
```

**Comment by Saransh-cpp** [comment]
The case for `numpy.square` for the object backend is handled here -
https://github.com/scikit-hep/vector/blob/06a733784d8df77d2fe4ad0f87051f725fd6a831/src/vector/backends/object.py#L519-L531

but it is never called -
https://github.com/scikit-hep/vector/blob/06a733784d8df77d2fe4ad0f87051f725fd6a831/src/vector/backends/object.py#L389-L390

It is handled with an `if` condition in the awkward backend, which should also be the case for the object backend -
https://github.com/scikit-hep/vector/blob/06a733784d8df77d2fe4ad0f87051f725fd6a831/src/vector/backends/awkward.py#L1496-L1513

I'll fix this.
