### ISSUE TITLE
`deltaangle` between identical vectors return nan

### ISSUE THREAD

**Issue by simonthor** [scikit-hep/vector#463]
### Vector Version

1.3.1

### Python Version

3.11.4

### OS / Environment

Kubuntu Linux 22.04 

### Describe the bug

When taking two identical vectors and computing the angle between them, I expect the result to be 0. Instead, I get NaN:
```python
> v = vector.obj(x=1, y=1, z=1)
> v.deltaangle(v)
nan
```
This is also true when using vector.array. I have not tried other backends.

**Comment by jpivarski** [comment]
Guidance from ROOT: this should return zero, rather than nan.

ROOT's [TVector3](https://root.cern.ch/doc/master/classTVector3.html) has an `Angle` method that returns zero for the same vector:

```python
>>> import ROOT
>>> a = ROOT.TVector3(1.1, 2.2, 3.3)
>>> a.Angle(a)
0.0
```

I wasn't able to find a generic "angle" method on [XYZVector](https://root.cern.ch/doc/master/classROOT_1_1Math_1_1DisplacementVector3D.html).

The issue is that in

https://github.com/scikit-hep/vector/blob/a9f1c7431a82289bac325d28d6fa4ab5ba4a8836/src/vector/_compute/spatial/deltaangle.py#L34-L37

the argument of `arccos` is supposed to be 1, but it's 1.0000000000000002. This is just an unfortunate round-off error: `vector.obj(x=3, y=4, z=0)` has a `v.dot(v) / v.mag**2` of precisely 1.0, and `vector.obj(x=3, y=4, z=5)` has 0.9999999999999999, for instance.

I think a good solution would be to clamp the argument of `arccos` to be within -1 and 1, since $(\vec{x} \cdot \vec{y}) / (|\vec{x}| |\vec{y}|)$ is provably within this range (barring round-off error). That is, instead of

```python
lib.arccos(ARG)
```

do

```python
lib.arccos(lib.maximum(-1, lib.minimum(1, ARG)))
```

(with `minimum` and `maximum` being identity functions for SymPy).

**Comment by Saransh-cpp** [comment]
Thanks for the explanation! Just to confirm - should `minimum` and `maximum` be the identity functions or `sympy.Min` and `sympy.Max` aliases for the SymPy? (`lib.maximum` points to `sympy.Max` at the moment)

**Comment by Saransh-cpp** [comment]
Thanks for the detailed explanation! I've updated the definitions for `lib.maximum` and `lib.minimum` in the same PR.
