### ISSUE TITLE
Link to coffea vector page doesn't work

### ISSUE THREAD

**Issue by dyl64** [scikit-hep/vector#535]
### Vector Version

N/A

### Python Version

N/A

### OS / Environment

MAC

### Describe the bug

In README, the link to [coffea.nanoevents.methods.vector](https://coffeateam.github.io/coffea/modules/coffea.nanoevents.methods.vector.html) doesn't work. The current link in the github will be linked to 404 page. They update their link but I'm not sure which one

**Comment by Saransh-cpp** [comment]
Nice catch! The link should be updated to - https://coffea-hep.readthedocs.io/en/latest/modules/coffea.nanoevents.methods.vector.html - with a note saying "backed by Scikit-HEP/vector since `v2024.8`"

Something like this -

..., and [coffea.nanoevents.methods.vector](https://coffea-hep.readthedocs.io/en/latest/modules/coffea.nanoevents.methods.vector.html) (backed by Scikit-HEP/vector since `v2024.8`).

@dyl64 would you be up to fix this issue?

**Comment by Ankush1oo8** [comment]
I have fixed the issue in PR #536

**Comment by Ankush1oo8** [comment]
I have fixed the Issue in PR  #537
I have also changed the link in docs/index.rst file
