### ISSUE TITLE
pip failed in environment.yml

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/vector#8]
I'm trying to build the conda dev env.

```bash
conda env create
jupyter lab
conda activate vector
conda config --env --add channels conda-forge
```

But `ModuleNotFoundError: No module named 'awkward1'` in notebooks/VectorDesignPrototype.ipynb.

P.S., I am using Python3 kernel. Is this related to jupyter kernel?

**Comment by henryiii** [comment]
You will need  `pip install awkward1` for now. Once awkward1 is finalized, we can provide a conda package for it; it's *just* finishing being developed.

**Comment by LovelyBuggies** [comment]
I think the `conda activate` has already installed the package. I run the following **after** the above commands:

```python3
(vector) NinodeMacBook-Pro:vector nino$ pip install awkward1
Requirement already satisfied: awkward1 in /Users/nino/anaconda3/envs/vector/lib/python3.8/site-packages (0.2.7)
Requirement already satisfied: numpy>=1.13.1 in /Users/nino/anaconda3/envs/vector/lib/python3.8/site-packages (from awkward1) (1.18.1)
```

And the notebooks still cannot import awkward1 for some reason.

**Comment by LovelyBuggies** [comment]
I am confused about the `enviroment.yml` when activating. I see it says:

```yml
  - pip:
    - "awkward1>=0.2.3,!=0.2.4"
    - "scikit-hep-testdata>=0.2.0"
    - -e .
```

Why do I not get `awkward1`, or why do I get `awkward1` 0.2.7 as shown (it should be 0.2.3 and not 0.2.4, shouldn't it)?

**Comment by jpivarski** [comment]
If `awkward1>=0.2.3,!=0.2.4` was written with the intention of `awkward1==0.2.3`, then it no longer works because there are higher versions than `0.2.4` now. I'm not releasing them as often as I did, but I just released `0.2.10` today.

What's holding you back to `0.2.3`? It's probably something that's been fixed. But the most immediate answer is that you probably want `awkward1==0.2.3`.

**Comment by LovelyBuggies** [comment]
Yep, I think this has something to do with jupyter kernel, I manually created a kernel named `vector` and used this. Then the notebooks worked.

**Comment by LovelyBuggies** [comment]
@jpivarski , why should use 0.2.3?

> What's holding you back to 0.2.3? It's probably something that's been fixed. But the most immediate answer is that you probably want awkward1==0.2.3.

I run with 0.2.7, but everything seems ok (at lease for the VectorDesign Prototype).

**Comment by jpivarski** [comment]
That's what I was saying. Whatever motivated the restriction to 0.2.3 is probably fixed by now or would be an easy fix, so you should switch to the latest version at your convenience. (I know that I caused an issue when I moved `awkward1._numba` to `awkward1._connect._numba`, but a major move like that isn't going to happen again. If necessary, you can adjust for it with a find-and-replace.)

Whenever possible, you want to use the latest versions of everything. ("Whenever possible" because sometimes the latest versions are broken, but that's something we try to fix right away.) The next significant change I see coming up is that Awkward1 will start requiring Numba 0.49 when Numba 0.49 is released in a week or two. (See https://github.com/scikit-hep/awkward-1.0/pull/189. I'm waiting for Numba 0.49—not a prerelease or release candidate—to be released in pip before making this change. But then it will be _necessary_ to switch to the latest version. Numba is moving submodules around, just as Awkward1 already did.)
