### ISSUE TITLE
Add version check for awkward

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/vector#81]
We should add a version check for awkward array, based on packaging + importlib_metadata/importlib.metadata. Also add an awkward extra.

_Originally posted by @jpivarski in https://github.com/scikit-hep/vector/issues/79#issuecomment-818031030_

**Comment by henryiii** [comment]
Since we don't have an `import vector.awkawrd` or similar, what should the behavior be when Awkward is too old? Breaking "normal" vector usage just because Awkward is installed and too old seems a bit harsh? Otherwise, though, then we'd have the "VectorAwkward" defined as None, etc.

**Comment by jpivarski** [comment]
If the version check is inside of `vector._backends.awkward_`, then users will only get the error message if they try to use a function in `vector` that uses it, such as `vector.awk`.

Oh, except for this:

https://github.com/scikit-hep/vector/blob/ecd31e57bd24938ade8a1da2807242e10ec6b0f9/src/vector/__init__.py#L52-L59

This, as written, would fail just for having the wrong version of Awkward and not using it, so that should only "`else: import vector._backends.awkward_` if the version is okay.
