### ISSUE TITLE
`MomentumArray4D ` via `ak.ArrayBuilder` forces x,y,z,t fields

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/vector#83]
This might just be a impl. detail  - if so please close (or I move it to discussion)

When building a `MomentumArray4D` with `ak.ArrayBuilder` with the `name` keyword argument, I need to be careful to use `x,y,z,t` fieldnames and not `px`,`py`,`pz`,`E` (which I would have expected given that I pass `MomentumArray4D` as a name)

cc @jpivarski as a continuation of the discussion in #83 

```
data = [
    {"px": 1., "py": 1.1, "pz": 0.1, 'E': 3.3},
    {"px": 2., "py": 2.2, "pz": 0.2, 'E': 3.3}
]


print(ak.type(vc.awk(data)))
print(vc.awk(data).mass)
print(vc.awk(data).px)

builder = ak.ArrayBuilder()
for d in data:
    with builder.record(name = 'Momentum4D'):
#        for f in d.keys():  fails
        for f,k in {'x':'px','y':'py','z': 'pz', 't': 'E'}.items():
            builder.field(f).real(d[k])
builder.snapshot().mass
```

**Comment by jpivarski** [comment]
PR #84 fixes this bug. The following now works:

```python
>>> import vector
>>> import awkward as ak
>>> data = [
...     {"px": 1., "py": 1.1, "pz": 0.1, 'E': 3.3},
...     {"px": 2., "py": 2.2, "pz": 0.2, 'E': 3.3}
... ]
>>> builder = ak.ArrayBuilder(behavior=vector._backends.awkward_.behavior)
>>> for d in data:
...     with builder.record(name = 'Momentum4D'):
...         for f in d.keys():
...             builder.field(f).real(d[f])
... 
>>> builder.snapshot().mass
<Array [2.94, 1.42] type='2 * float64'>
```

@henryiii The `builder = ak.ArrayBuilder(behavior=vector._backends.awkward_.behavior)` line is another argument for introducing `vector.awkward`, so that it can be just `vector.awkward.behavior`. We can add such a publicly facing module before deprecating top-level `VectorAwkward` (and it would allow for a smooth transition).
