### ISSUE TITLE
`vector.Array`/`vector.awk` should be implicitly zipped(?)

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/vector#93]
I'm running into several places where `vector.Array` (or `vector.awk`) either doesn't work or doesn't behave as I would expect if I don't use `ak.zip()` first. This makes me think that `vector.Array`/`vector.awk` should implicitly `zip` where needed.

Examples:

```python
>>> import awkward as ak
>>> import vector
>>> v = vector.Array({"x": [[], [1]], "y": [[], [1]]})
>>> v
<VectorArray2D [{x: [], y: []}, {x: [1], y: [1]}] type='2 * Vector2D["x": var * ...'>
>>> vz = vector.Array(ak.zip({"x": [[], [1]], "y": [[], [1]]}))
>>> vz
<VectorArray2D [[], [{x: 1, y: 1}]] type='2 * var * Vector2D["x": int64, "y": in...'>
>>> ak.num(v)
<Array [{x: 0, y: 0}, {x: 1, y: 1}] type='2 * {"x": int64, "y": int64}'>
>>> ak.num(vz)
<Array [0, 1] type='2 * int64'>
```

The `vz` result is what I want, where the vectors are treated as the primitive elements of the array. After all, the construction doesn't even make sense if `x` and `y` here don't match lengths everywhere. The same kind of issue applies to any function dealing with indices such as `ak.argcombinations` or `ak.local_index`.

The unzipped version also can't be flattened:

```python
>>> ak.flatten(v)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/awkward/operations/structure.py", line 1904, in flatten
    out = layout.flatten(axis)
ValueError: arrays of records cannot be flattened (but their contents can be; try a different 'axis')

(https://github.com/scikit-hep/awkward-1.0/blob/1.2.2/src/libawkward/array/RecordArray.cpp#L1107)
>>> ak.flatten(vz)
<VectorArray2D [{x: 1, y: 1}] type='1 * Vector2D["x": int64, "y": int64]'>
```

This prevents `ak.cartesian` and `ak.argcartesian` from working as well.

Also, concatenating the unzipped version along a non-zero axis with another `VectorArray2D` returns a plain `Array` rather than a new `VectorArray2D`:

```python
>>> ak.concatenate((v, v), axis=1)
<Array [{x: [], y: []}, ... 1, 1], y: [1, 1]}] type='2 * {"x": var * int64, "y":...'>
>>> ak.concatenate((vz, vz), axis=1)
<VectorArray2D [[], [{x: 1, y: 1}, {x: 1, y: 1}]] type='2 * var * Vector2D["x": ...'>
```

**Comment by jpivarski** [comment]
Okay, I see why it's doing this and what you want instead, but that's because the `vector.Array` constructor behaves exactly like the `ak.Array` constructor. I think it would be more confusing if the two of them did slightly different things, and the `ak.Array` constructor from a dict is designed to work like the `pd.DataFrame` constructor (requested by @henryiii), in which each value in the dict is interpreted as a column. The `ak.Array` constructor shouldn't change because that's the key difference between `ak.Array` and `ak.zip`.

I think what this means, then, is that you want a `vector.zip`, which would determine the dimensionality and flavor (generic vs momentum) of the array from the supplied field names, but zip the arguments, rather than taking them as columns. That might even solve our dilemma about how to name the `vector.Array` function (it's not a class, so technically shouldn't be capitalized), because `vector.zip` sounds more useful than `vector.Array`.

**Comment by jpivarski** [comment]
So how's this?

https://github.com/scikit-hep/vector/blob/6a7c5c56a6dbfdca150b3fee8931124538bee693/tests/backends/test_awkward.py#L180-L187

There's a pretty good chance that `vector.zip` would be used a lot more than `vector.Array` (or whatever it ends up being named). In fact, that would be yet more reason to add a public-facing `vector.awkward` module:

```python
>>> import vector                                 # no Awkward stuff gets loaded
>>> import vector.awkward                         # now it's loaded, but ak.behavior is not modified

>>> vector.zip({"x": [[], [1]], "y": [[], [1]]})  # this also would load Awkward, if not done already
<VectorArray2D [[], [{x: 1, y: 1}]] type='2 * var * Vector2D["x": int64, "y": in...'>

>>> vector.awkward.register()                     # actually changes ak.behavior globally

>>> # This is somewhat more buried because it can be used to create arrays that don't make sense.
>>> vector.awkward.Array({"x": [[], [1]], "y": [[], [1]]})
<VectorArray2D [{x: [], y: []}, {x: [1], y: [1]}] type='2 * Vector2D["x": var * ...'>
```

**Comment by henryiii** [comment]
`vector.awkward.zip`?

**Comment by jpivarski** [comment]
It's a lot to type. The NumPy constructors are imported at top-level, and I think this would be the most-used Awkward constructor.

**Comment by jpivarski** [comment]
I'll leave it to you to decide if PR #94 is an acceptable interface and merge it.

Considering that the Pandas-style interface to `ak.Array` is equivalent to `ak.zip` with `depth_limit=1`, `vector.zip` (or `vector.awkward.zip`) can replace `vector.Array` in most circumstances. The only reason you'd still want a function like `vector.Array` (or `vector.awkward.Array` or `vector.arr` or `vector.awk`) is to use its other signatures, in which the argument is a NumPy array, an iterable, or low-level `ak.layout.Content`. That's why it should still exist, but maybe be less prominent, since the Pandas-style interface can make arrays that aren't usable as vectors.
